config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "stages#index"
  resources :stages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stage.rb
class Stage < ApplicationRecord

  with_options presence: true do
    #validates :image
    validates :category
    validates :title
    validates :group
    validates :time
    validates :start_day
    validates :end_day
    validates :theater
    validates :advance_price
    validates :regular_price
    #validates :writer
    #validates :director
    validates :cast
    #validates :text
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  def index
    @stages = Stage.all
  end

  def new
    @stage = Stage.new
  end

  def create
    @satge = Stage.new(stage_params)
    if @satge.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def stage_params
    params.require(:stage).permit(:image, :category, :title, :group, :time, :start_day, :end_day, :theater, :advance_price, :regular_price, :writer, :director, :cast, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>★Come Stage!</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">


    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
  </head>

  <body>
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-4 offset-md-1 py-4">
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">プロフィール変更</a></li>
            <li><a href="#" class="text-white">公演カレンダー</a></li>
            <li><a href="#" class="text-white">詳細検索</a></li>
            <li><a href="#" class="text-white">ランキング</a></li>
            <li><a href="stages/new" class="text-white">公演掲載</a></li>
            <li><a href="#" class="text-white">ヘルプ</a></li>
          </ul>
        </div>
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Come Stage! とは？</h4>
          <p class="text-white">芸能の世界で活動をされている皆さんにとって、広く世の中に発信のできる場となることを願っています。</p>
          <p>
            <a href="#" class="btn btn-danger my-2">演劇</a>
            <a href="#" class="btn btn-danger my-2">LIVE</a>
            <a href="#" class="btn btn-danger my-2">お笑い</a>
            <a href="#" class="btn btn-danger my-2">ミュージカル</a>
            <a href="#" class="btn btn-danger my-2">オペラ</a>
            <a href="#" class="btn btn-danger my-2">落語</a>
            <a href="#" class="btn btn-danger my-2">ダンス</a>
            <a href="#" class="btn btn-danger my-2">演芸</a>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span >MENU</span>
      </button>
      <a href="/" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"></svg>
        <h1>★Come Stage!</h1>
      </a>
      <p>
        <a href="#" class="btn btn-primary my-2">新規登録</a>
        <a href="#" class="btn btn-secondary my-2">ログイン</a>
      </p>
    </div>
  </div>
</header>
<%= yield %>
<footer class="text-muted py-5 bg-dark">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#" class="text-white">トップに戻る</a>
    </p>
    <ul class="list-unstyled">
      <li class="list-inline-item"><a href="#" class="text-white">利用規約</a></li>
      <li class="list-inline-item"><a href="#" class="text-white">プライバシーポリシー</a></li>
      <li class="list-inline-item"><a href="#" class="text-white">運営会社</a></li>
      <li class="list-inline-item"><a href="#" class="text-white">お問い合わせ</a></li>
      <li class="list-inline-item"><a href="#" class="text-white">ヘルプ</a></li>
    </ul>
  </div>
</footer>





    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="form-validation.js"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/stages/index.html.erb
<main>
  <div class="album py-5 bg-dark">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% @stages.each do |stage| %>
          <div class="col">
          <%= link_to stage_path(stage) do %>
            <div class="card shadow-sm">
              <img src="<%= stage.image %>">
              <div class="card-body">
                <p class="card-text text-dark">作品名:<%= stage.title %></p>
                <p class="card-text text-dark">劇場名:<%= stage.theater %></p>
                <p class="card-text text-dark">公演期間:<%= stage.start_day %>〜<%= stage.end_day %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="count">
                    <small class="text-muted text-dark"><%= stage.group %></small>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/stages/new.html.erb
<main class="py-5 bg-dark text-white">

  <div class="col-md-7 col-lg-8 d-block mx-auto mb-4">
    <h2>公演を掲載する</h2>
    <p class="lead">あなたの上演する公演の詳細を入力することができます。</p>
    <p class="lead">ここに入力された情報を元に公演を掲載させていただきます。</p>
  </div>

  <div class="col-md-7 col-lg-8 d-block mx-auto mb-4">
    <h4 class="mb-3">掲載内容</h4>
    <%= form_with(model: @stage, local: true) do |form| %>

      <div class="row g-4">
        <div class="order-md-last">

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="image" class="form-label">フライヤー:</label>
            <%= form.text_field :image, placeholder: "公演チラシのURLを貼り付けてください", size: 70 %>
          </div>

          <hr class="my-4">

          <div class="col-md-6">
            <label for="category" class="form-label">カテゴリー:</label>
            <%= form.text_field :category, placeholder: "ジャンル選択してください。", size: 70 %>
            <div class="invalid-feedback">
              ジャンル選択してください。
            </div>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="title" class="form-label">作品タイトル:</label>
            <%= form.text_field :title, placeholder: "タイトルを入力してください。", size: 70 %>
            <div class="invalid-feedback">
              公演名を入力してください
            </div>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="group" class="form-label">団体・グループ名:</label>
            <%= form.text_field :group, placeholder: "団体・グループ名を入力してください。", size: 70 %>
            <div class="invalid-feedback">
              団体名を入力してください
            </div>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="time" class="form-label">上演時間:</label>
            <%= form.text_field :time, placeholder: "上演時間を入力してください。", size: 70 %>
            <div class="invalid-feedback">
              上演時間を入力してください
            </div>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="start_day" class="form-label">公演初日:</label>
            <%= form.date_select :start_day, use_month_numbers: true, size: 70 %>
            <div class="invalid-feedback">
              公演初日を選択してください
            </div>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="end_day" class="form-label">公演楽日:</label>
            <%= form.date_select :end_day, use_month_numbers: true, size: 70 %>
            <div class="invalid-feedback">
              公演楽日を入力してください
            </div>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="theater" class="form-label">劇場名(最寄駅名):</label>
            <%= form.text_field :theater, placeholder: "劇場名(最寄駅名)を入力してください。", size: 70 %>
            <div class="invalid-feedback">
              劇場名(最寄駅名)を入力してください
            </div>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="advance_price" class="form-label">前売り券料金:</label>
            <%= form.text_field :advance_price, placeholder: "前売り券の金額を入力してください。", size: 70 %>
            <div class="invalid-feedback">
              前売り券の金額を入力してください
            </div>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="regular_price" class="form-label">当日券料金:</label>
            <%= form.text_field :regular_price, placeholder: "当日券の金額を入力してください。", size: 70 %>
            <div class="invalid-feedback">
              当日券の金額を入力してください
            </div>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="writer" class="form-label">脚本家名:</label>
            <%= form.text_field :writer, placeholder: "脚本家名を入力してください。", size: 70 %>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="director" class="form-label">演出家名:</label>
            <%= form.text_field :director, placeholder: "演出家名を入力してください。", size: 70 %>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="cast" class="form-label">出演者名:</label>
            <%= form.text_area :cast, placeholder: "出演者名を入力してください。", :size => "70x10" %>
            <div class="invalid-feedback">
              出演者名を入力してください
            </div>
          </div>

          <hr class="my-4">

          <div class="col-sm-12">
            <label for="text" class="form-label">その他の情報:</label>
            <%= form.text_area :text, placeholder: "その他の情報を入力してください。", :size => "70x10" %>
          </div>

          <hr class="my-4">

          <%= form.submit "公演を掲載する" %>
        </div>
      </div>
    <% end %>
  </div>
</main>